### ISSUE TITLE
TODO: gradlew signingReport error

### ISSUE THREAD

**Issue by khalim-N** [koalaman/shellcheck#2030]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2148, SC2154, SC1036, SC1088
- My shellcheck version (`shellcheck --version` or 'online'): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### For new checks and feature suggestions
- [x] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [ ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile"$Source".zerror(ZipFile.java:1482)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1383)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1390)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1221)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1184)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:238)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:168)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:182)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

#### Here's what shellcheck currently says:
```
Line 1	SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
Line 2	SC2154: Source is referenced but not assigned.
Line 2	SC1036: '(' is invalid here. Did you forget to escape it?
Line 2	SC1088: Parsing stopped here. Invalid use of parentheses?
```
#### Here's what I wanted or expected to see:

TODO: Describe expected/desired output

**Comment by brother** [comment]
Fairly sure that's not shell syntax =)

Maybe fix your build zip thing stuff first and then try shellcheck.net again.

@koalaman issue reported in error. close.

**Comment by khalim-N** [comment]
> Fairly sure that's not shell syntax =)
> 
> Maybe fix your build zip thing stuff first and then try shellcheck.net again.
> 
> @koalaman issue reported in error. close.

ok
