### ISSUE TITLE
shellcheck-py installation fails with python 3.9.1 on Mac M1

### ISSUE THREAD

**Issue by arthurvasconcelos** [koalaman/shellcheck#2174]
#### Versions:

```sh

pyenv --version
# pyenv 1.2.23

python --version
# Python 3.9.1

pip --version
# pip 21.0.1

poetry --version
# Poetry version 1.1.5

```

#### Installation output:

```
  • Installing shellcheck-py (0.7.1.1): Failed

  EnvCommandError

  Command ['/Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/arthur/Library/Caches/pypoetry/artifacts/ee/51/0f/26f88a282e231a2d30fdbb317874d09d9487ab1eb429845789eba208c1/shellcheck_py-0.7.1.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/arthur/Library/Caches/pypoetry/artifacts/ee/51/0f/26f88a282e231a2d30fdbb317874d09d9487ab1eb429845789eba208c1/shellcheck_py-0.7.1.1.tar.gz
  Building wheels for collected packages: shellcheck-py
    Building wheel for shellcheck-py (setup.py): started
    Building wheel for shellcheck-py (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-wheel-4fr2p1px
         cwd: /private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/
    Complete output (34 lines):
    running bdist_wheel
    running build
    running fetch_binaries
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py", line 163, in <module>
        setup(version=f'{SHELLCHECK_VERSION}.{PY_VERSION}', cmdclass=command_overrides)
      File "/Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
        self.run_command('build')
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py", line 111, in run
        data = extract(url, archive)
      File "/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py", line 62, in extract
        with tarfile.open(fileobj=bio) as tarf:
      File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/tarfile.py", line 1616, in open
        raise ReadError("file could not be opened successfully")
    tarfile.ReadError: file could not be opened successfully
    ----------------------------------------
    ERROR: Failed building wheel for shellcheck-py
    Running setup.py clean for shellcheck-py
  Failed to build shellcheck-py
  Installing collected packages: shellcheck-py
      Running setup.py install for shellcheck-py: started
      Running setup.py install for shellcheck-py: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-record-0_nofc5h/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/include/site/python3.9/shellcheck-py
           cwd: /private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/
      Complete output (36 lines):
      running install
      running build
      running fetch_binaries
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py", line 163, in <module>
          setup(version=f'{SHELLCHECK_VERSION}.{PY_VERSION}', cmdclass=command_overrides)
        File "/Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/install.py", line 546, in run
          self.run_command('build')
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py", line 111, in run
          data = extract(url, archive)
        File "/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py", line 62, in extract
          with tarfile.open(fileobj=bio) as tarf:
        File "/Users/arthur/.pyenv/versions/3.9.1/lib/python3.9/tarfile.py", line 1616, in open
          raise ReadError("file could not be opened successfully")
      tarfile.ReadError: file could not be opened successfully
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-req-build-3d15gqdu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7p/btbr82r13qd2jr52n6gm9smr0000gn/T/pip-record-0_nofc5h/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arthur/Library/Caches/pypoetry/virtualenvs/kog-W0XsUAqJ-py3.9/include/site/python3.9/shellcheck-py Check the logs for full command output.
  

  at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):
```

**Comment by arthurvasconcelos** [comment]
I've just noticed that I should have opened this on shellcheck-py repo. Sorry for the mistake.
